CREATE TABLE `user` (
	`user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(100) NULL DEFAULT NULL,
	`password` VARCHAR(250) NULL DEFAULT NULL,
	`nama_lengkap` VARCHAR(100) NULL DEFAULT NULL,
	`jurusan` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`user_id`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
